# Generated by Django 4.1 on 2022-09-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_category_name_en_category_name_ru"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterIndexTogether(
            name="product",
            index_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="Products",
            field=models.ManyToManyField(to="shop.product"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
    ]
