# Generated by Django 4.1 on 2022-09-11 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_product_options_alter_product_index_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("name",)},
        ),
        migrations.RemoveField(
            model_name="category",
            name="Products",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterIndexTogether(
            name="product",
            index_together={("id", "slug")},
        ),
    ]
