# Generated by Django 4.1 on 2022-09-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_product_options_remove_category_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
